version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
  cooldown: 1 day
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  cooldown: 1 day
